[package]
name = "libkls"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
console_error_panic_hook = "0.1"
keid = { path = "../../../keid" }

[lib]
name = "libkls"
crate-type = ["cdylib"]

[profile.release]
debug = true
